// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACtL4-SHx2YXmuVsoWUp8irYo-7OYhyII',
    appId: '1:618640109046:web:f82cf058193ed83a05ebd7',
    messagingSenderId: '618640109046',
    projectId: 'firsttry-5c942',
    authDomain: 'firsttry-5c942.firebaseapp.com',
    storageBucket: 'firsttry-5c942.firebasestorage.app',
    measurementId: 'G-VB10LD145R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpETEmU3QE8jEZ6AFRFwpf-pgEXXNhpA',
    appId: '1:618640109046:android:8496797fa0cf427305ebd7',
    messagingSenderId: '618640109046',
    projectId: 'firsttry-5c942',
    storageBucket: 'firsttry-5c942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdYNQtsFErDAQArCc2Bgzloui2TRo1JE',
    appId: '1:618640109046:ios:d7a6d375b7682c5505ebd7',
    messagingSenderId: '618640109046',
    projectId: 'firsttry-5c942',
    storageBucket: 'firsttry-5c942.firebasestorage.app',
    iosBundleId: 'com.example.firsttry',
  );
}
